  version: '3.8'

  services:
    web:
      build: .
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./:/usr/src/venueGuide_backend
      ports:
        - 8000:8000
      env_file:
        - ./.env.dev
      depends_on:
        - db
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgresuser
        - POSTGRES_PASSWORD=postgrespassword
        - POSTGRES_DB=venueGuide_backend


  volumes:
    postgres_data: